language: ruby
matrix:
  include:
  - rvm: ruby-head
    env:
      - LABEL=unit_tests
  - rvm: 2.3.0
    env:
      - LABEL=unit_tests
  - rvm: 2.3.0
    env:
      - LABEL=docker_build
    services:
      - docker
    script:
      - docker build -t mozilla/ssh_scan .
      - >
          if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then \
            docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" ;\
            docker push mozilla/ssh_scan:latest ;\
          else \
            exit 0 ;\
          fi
  - rvm: 2.3.0
    env:
      - LABEL=gem_install_latest
    script:
      - gem install ssh_scan
  - rvm: 2.3.0
    env:
      - LABEL=integration_tests
    script:
      - chmod 755 ./spec/ssh_scan/integration.sh
      - ./spec/ssh_scan/integration.sh
  - rvm: 2.2.0
    env:
      - LABEL=unit_tests  
  - rvm: 2.1.3
    env:
      - LABEL=unit_tests  
  - rvm: 2.0.0
    env:
      - LABEL=unit_tests
