language: ruby
matrix:
  include:
  - rvm: ruby-head
    env:
      - LABEL=enforce_signed_commits
    script:
      - chmod 755 ./spec/ssh_scan/enforce_signed_commits.rb
      - ./spec/ssh_scan/enforce_signed_commits.rb
  - rvm: ruby-head
    env:
      - LABEL=unit_tests
  - rvm: 2.3.0
    env:
      - LABEL=unit_tests
  - rvm: 2.2.0
    env:
      - LABEL=unit_tests
  - rvm: 2.1.3
    env:
      - LABEL=unit_tests
  - rvm: 2.0.0
    env:
      - LABEL=unit_tests
  - rvm: 2.3.0
    env:
      - LABEL=gem_integration_tests
    script:
      - gem install ssh_scan
      - chmod 755 ./spec/ssh_scan/integration.sh
      - ./spec/ssh_scan/integration.sh
  - rvm: 2.3.0
    env:
      - LABEL=src_integration_tests
    script:
      - bundle install
      - chmod 755 ./spec/ssh_scan/integration.sh
      - ./spec/ssh_scan/integration.sh
  - rvm: 2.3.0
    env:
      - LABEL=docker_build_push
    services:
      - docker
    script:
      - docker build -t mozilla/ssh_scan .
      - >
          if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then \
            docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" ;\
            docker push mozilla/ssh_scan:latest ;\
          else \
            exit 0 ;\
          fi

branches:
  only:
    - master
  before_deploy:
    - bundle exec rake package
  deploy:
    provider: releases
    api_key:
      secure: $GITHUB_OAUTH_TOKEN
    file:
      - "ssh_scan-#{$TRAVIS_TAG}-linux-x86.tar.gz"
      - "ssh_scan-#{$TRAVIS_TAG}-linux-x86_64.tar.gz"
      - "ssh_scan-#{$TRAVIS_TAG}-osx.tar.gz"
      - "ssh_scan-#{$TRAVIS_TAG}-win32.tar.gz"
    skip_cleanup: true
    on:
      tags: true
  after_deploy:
    - echo "Binary Artifacts Released successfully"
